#!/bin/bash
clear
#--------@Modderajuda-----------#
source ShellBot.sh
touch lista
[[ -z $1 ]] && {
    clear && echo "INFORME O TOKEN" && return 0
}
[[ ! -e RESET ]] && touch RESET
api_bot=$1
ShellBot.init --token "$api_bot" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
        msg+="<b>🤖 SEA BIENVENIDO(A)! 🤖</b>\n"
        msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
        msg+="<b>CONSEJO: PARA GENERAR UN INICIO DE SESIÓN DE PRUEBA HAGA CLIC EN EL BOTÓN (GENERAR PRUEBA GRATIS)\n\nPODRÁ GENERAR UN INICIO DE SESIÓN CADA 6 HORAS"
        msg+="\n\n=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
        msg+="<b>É PROHIBIDO EL USO DE TORRENT. AL SER DETECTADO USANDO TORRENT, SU CUENTA SERÁ CANCELADA!</b>\n\n"
        msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
        msg+="<b>AYÚDANOS A CONTINUAR CON ESTE PROYECTO (DEPÓSITA AQUÍ) ❤️</b>\n\n"
        msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×="
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - funcao criar ssh
criarteste() {
    [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "USTED YA CREÓ UNA CUENTA HOY, VUELVA EN 24 HORAS !"
      return 0
    }
    usuario=$(echo teste$(( RANDOM% + 9999 + 1111 )))
    senha=$((1234))
    limite='2'
    dias='6'
    tuserdate=$(date '+%C%y/%m/%d' -d " +6 hours")
    useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
    chmod +x /etc/SSHPlus/userteste/$usuario.sh
    at -f /etc/SSHPlus/userteste/$usuario.sh now + $dias hour > /dev/null 2>&1
    echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "🤩 <b>LOGIN CRIADO</b> 🤩 \r\n\r\n🚻 <b>USUARIO:</b> <code>$usuario</code>\r\n🔐 <b>SENHA:</b> <code>$senha</code>\r\n❌ <b>LIMITE:</b> 1\r\n<b>⏰ VALIDADE:</b> $dias Horas \r\n\r\n<b>BAIXE O APLICATIVO MAIS RECENTE NO NOSSO GRUPO E FIQUE POR DENTRO DAS NOVIDADES.</b>\r\n\r\n<b>ACESSE O NOSSO GRUPO</b> @shume22\r\n\r\n<b>ACESSE O NOSSO CANAL</b> @+S7QAM20MziViMjdh")" \
    --parse_mode html
    return 0
}

#comprarmensal
buylogin() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ AGUARDE..."
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "<b>MUCHAS GRACIAS POR CONFIAR EN MI TRABAJO</b>\r\n<b>REALICE EL PAGO Y ENVÍE EL COMPROBANTE A</b>👉 @shume22 👈\r\n<b>👇 Bac Credomatic 👇</b>\r\n<b>102375847</b> 102375847 ")" \
    --parse_mode html
    return 0
}

#enviar app
enviarapp() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ ENVIANDO APLICATIVO, AGUARDE..."
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/donomodderajuda.apk" \
    return 0
}
    
#comprar o mod
buymod() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ AGUARDE..."
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "<b>🛒 ¡Cuentas SSH y V2RAY Disponibles!.</b>\r\n\r\n<b>DISPONIBLES PARA 31 DIAS SIN CAIDAS</b>👉 @shume22\r\n\r\n<b>CONTACTANOS 100 SIN CAIDAS</b>👉 @ShumeloSSH")" \
    --parse_mode html
    return 0
}

#fazer pix
obapix() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ AGUARDE..."
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "$(echo -e "<b>MUCHAS GRACIAS POR APOYAR NUESTRO PROYECTO.</b>\r\n\r\n<b>DONE CUALQUIER CANTIDAD PARA AYUDARNOS A CONTINUAR CON ESTE Y OTROS PROYECTOS.</b>")" \
    --parse_mode html
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "👇 CLAVE DEL BAC A NOMBRE DE : <b>Omar Campos</b>👇\r\n\r\n<b>Toque na chave abaixo para copiá-la</b>" \
        --parse_mode html
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "<code>102375847</code>" \
        --parse_mode html
    return 0
}

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nome:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUser: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text '♻️ GENERAR PRUEBA GRATIS ♻️' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 5 --text '🔰 DESCARGAR APLICACIÓN 🔰' --callback_data 'appenviar'
ShellBot.InlineKeyboardButton --button 'botao1' --line 7 --text '💵 COMPRAR USUARIOS SSH 💵' --callback_data 'comprarmod'
ShellBot.InlineKeyboardButton --button 'botao1' --line 9 --text '🤞 APOYAR PROYECTO 🙏️' --callback_data 'fazerpix'
ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function buylogin --callback_data buymensal
ShellBot.regHandleFunction --function enviarapp --callback_data appenviar
ShellBot.regHandleFunction --function buymod --callback_data comprarmod
ShellBot.regHandleFunction --function obapix --callback_data fazerpix
unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"
while :; do
   [[ "$(date +%d)" != "$(cat RESET)" ]] && {
   	echo $(date +%d) > RESET
   	echo ' ' > lista
   }
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 24
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start" ]] && menu
      [[ "${comando[0]}" = "/id"  ]] && infouser
    ) &
  done
done
